### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by StefanArts** [WiIIiam278/Velocitab#124]
I've got this error in my Velocitab Console
```
[17:06:31 ERROR]: Exception in task net.william278.velocitab.tab.PlayerTabList$$Lambda$4098/0x00007f554d1d4ff0@775d8510 by plugin Velocitab
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1784) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.velocitypowered.proxy.tablist.VelocityTabList.getEntries(VelocityTabList.java:171) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at net.william278.velocitab.tab.PlayerTabList.lambda$onPlayerJoin$8(PlayerTabList.java:120) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by alexdev03** [comment]
Do you get it very often? This is a velocity bug with thread synchronization.
