### ISSUE TITLE
 Couldn't pass ProxyInitializeEvent to velocitab

### ISSUE THREAD

**Issue by tarkh** [WiIIiam278/Velocitab#137]
Hello! Getting this error in console while trying to start server.
- velocity-3.2.0-SNAPSHOT-296
- Velocitab-1.5.2

Thanks for plugin and any help on this issue!

```
[14:02:04 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-07a525be-b296)...
[14:02:05 INFO]: Loading localizations...
[14:02:05 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 3.0.x (Linux x86_64) ciphers
[14:02:05 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[14:02:05 INFO]: Loading plugins...
[14:02:06 INFO]: Loaded plugin fastmotd 1.0.31 by Elytrium (https://elytrium.net/)
[14:02:06 INFO] [floodgate]: Took 300ms to boot Floodgate
[14:02:06 INFO]: Loaded plugin floodgate 2.2.2-SNAPSHOT (b85-71acc6c) by GeyserMC
[14:02:06 INFO]: Loaded plugin geyser 2.2.0-SNAPSHOT (git-master-cdb8ab3) by GeyserMC
[14:02:06 INFO] [limboapi]: Initializing Simple Virtual World system...
[14:02:07 INFO] [limboapi]: Hooking into EventManager, PlayerList/UpsertPlayerInfo and StateRegistry...
[14:02:07 INFO]: Loaded plugin limboapi 1.1.17 by Elytrium (https://elytrium.net/)
[14:02:07 INFO]: Loaded plugin limboauth 1.1.14-SNAPSHOT (git-1dbca38) by Elytrium (https://elytrium.net/)
[14:02:07 INFO]: Loaded plugin luckperms 5.4.113 by Luck
[14:02:07 INFO]: Loaded plugin papiproxybridge 1.4.2 by William278
[14:02:07 INFO] [reconnect]: Couldn't find a storage method to use! Using default: 'yaml'
[14:02:08 INFO] [reconnect]: Running the latest version! ReconnectVelocity 1.3
[14:02:08 INFO]: Loaded plugin reconnect 1.3 by MattMX
[14:02:08 INFO]: Loaded plugin serverpermissions 1.3.1 by 4drian3d
[14:02:08 INFO]: Loaded plugin skinsrestorer 15.0.4 by knat, AlexProgrammerDE, Blackfire62, McLive
[14:02:08 INFO] [slashhub]: ----------------------------
[14:02:08 INFO] [slashhub]: 
[14:02:08 INFO] [slashhub]:   * SlashHub Velocity by SkyGameZ *
[14:02:08 INFO] [slashhub]:     * Version 1.5.1 *
[14:02:08 INFO] [slashhub]: 
[14:02:08 INFO] [slashhub]: ----------------------------
[14:02:08 INFO]: Loaded plugin slashhub 1.5.1 by skygamez
[14:02:08 INFO]: Loaded plugin velocitab 1.5.2 by William278
[14:02:08 INFO]: Loaded 12 plugins
[14:02:08 INFO]:         __    
[14:02:08 INFO]:   |    |__)   LuckPerms v5.4.113
[14:02:08 INFO]:   |___ |      Running on Velocity - Velocity
[14:02:08 INFO]: 
[14:02:08 INFO] [luckperms]: Loading configuration...
[14:02:09 INFO] [luckperms]: Loading storage provider... [MARIADB]
[14:02:09 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
[14:02:09 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
[14:02:09 INFO] [luckperms]: Loading messaging service... [SQL]
[14:02:09 INFO] [luckperms]: Loading internal permission managers...
[14:02:09 INFO] [luckperms]: Performing initial data load...
[14:02:09 INFO] [luckperms]: Successfully enabled. (took 1077ms)
[14:02:09 INFO] [fastmotd]: Hooked into ServerChannelInitializer
[14:02:10 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[14:02:10 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[14:02:10 INFO] [geyser]: Loading extensions...
[14:02:10 INFO] [geyser]: Loaded 0 extension(s)
[14:02:10 INFO] [limboapi]: Creating and preparing packets...
[14:02:10 INFO] [limboapi]: Loaded!
[14:02:11 INFO] [papiproxybridge]: PAPIProxyBridge (Velocity) has been enabled!
[14:02:11 INFO] [serverpermissions]: ServerPermissions has been correctly started
[14:02:11 INFO] [skinsrestorer]: Connected to MySQL!
[14:02:11 INFO] [skinsrestorer]: Floodgate skin listener registered
[14:02:12 INFO] [skinsrestorer]: ----------------------------------------------
[14:02:12 INFO] [skinsrestorer]:     +==================+
[14:02:12 INFO] [skinsrestorer]:     |   SkinsRestorer  |
[14:02:12 INFO] [skinsrestorer]:     +==================+
[14:02:12 INFO] [skinsrestorer]: ----------------------------------------------
[14:02:12 INFO] [skinsrestorer]:     Version: 15.0.4
[14:02:12 INFO] [skinsrestorer]:     Commit: 677e967
[14:02:12 INFO] [skinsrestorer]:     This is the latest version!
[14:02:12 INFO] [skinsrestorer]: ----------------------------------------------
[14:02:12 INFO] [velocitab]: Successfully hooked into LuckPerms
[14:02:12 INFO] [velocitab]: Successfully hooked into PAPIProxyBridge
[14:02:12 ERROR]: Couldn't pass ProxyInitializeEvent to velocitab
java.lang.IllegalStateException: Failed to register scoreboard packet adapters. Try to update velocity to latest build
        at net.william278.velocitab.packet.ScoreboardManager.registerVersions(ScoreboardManager.java:62) ~[?:?]
        at net.william278.velocitab.packet.ScoreboardManager.<init>(ScoreboardManager.java:52) ~[?:?]
        at net.william278.velocitab.Velocitab.prepareScoreboardManager(Velocitab.java:172) ~[?:?]
        at net.william278.velocitab.Velocitab.onProxyInitialization(Velocitab.java:94) ~[?:?]
        at net.william278.velocitab.Lmbda$22.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: java.lang.NoSuchFieldError: MINECRAFT_1_20_3
        at net.william278.velocitab.packet.Protocol765Adapter.<init>(Protocol765Adapter.java:37) ~[?:?]
        at net.william278.velocitab.packet.ScoreboardManager.registerVersions(ScoreboardManager.java:57) ~[?:?]
        ... 10 more
```

**Comment by alexdev03** [comment]
Hi, like the error says, update velocity to the latest build.

**Comment by WiIIiam278** [comment]
Please update Velocity to v3.3.0 :-)
