### ISSUE TITLE
Offline player is not removed from tab

### ISSUE THREAD

**Issue by waterghost-2046** [WiIIiam278/Velocitab#139]
<img width="325" alt="스크린샷 2024-01-10 오후 5 36 29" src="https://github.com/WiIIiam278/Velocitab/assets/115847965/66ee5f54-bc03-47d1-977a-5a3b9fadf6b3">
The number of online players and the number of nicknames do not match and do not actually match.
#121 Might be related to this issue

**Comment by WiIIiam278** [comment]
@waterghost-2046 Can you attempt to reproduce this in Velocitab v1.6.1?

**Comment by waterghost-2046** [comment]
There was a problem running the update to reproduce
`java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/UpsertPlayerInfoPacket
	at net.william278.velocitab.packet.PlayerChannelHandler.write(PlayerChannelHandler.java:42) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:230) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.handle(ConfigSessionHandler.java:195) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.protocol.packet.PluginMessage.handle(PluginMessage.java:104) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfoPacket
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 49 more`

**Comment by waterghost-2046** [comment]
I tried deleting the config and the plugin folder, but it didn't work.

**Comment by alexdev03** [comment]
> There was a problem running the update to reproduce `java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/UpsertPlayerInfoPacket at net.william278.velocitab.packet.PlayerChannelHandler.write(PlayerChannelHandler.java:42) ~[?:?] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:230) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.handle(ConfigSessionHandler.java:195) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.protocol.packet.PluginMessage.handle(PluginMessage.java:104) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at java.lang.Thread.run(Thread.java:1589) [?:?] Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfoPacket at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-316.jar:3.3.0-SNAPSHOT (git-408b420a-b316)] at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] ... 49 more`

Update velocity to latest build

**Comment by waterghost-2046** [comment]
<img width="279" alt="스크린샷 2024-01-23 오전 7 38 09" src="https://github.com/WiIIiam278/Velocitab/assets/115847965/842e80b3-5dd2-4715-ad8d-91e0fadcfe2b">

**Comment by alexdev03** [comment]
[Velocitab-1.6.1-91654ac-indev.zip](https://github.com/WiIIiam278/Velocitab/files/14029344/Velocitab-1.6.1-91654ac-indev.zip)
Hi could you try this dev version please?

**Comment by WiIIiam278** [comment]
We believe this is closed by #149 and v1.6.2, if the issue persists please let us know.

**Comment by waterghost-2046** [comment]
<img width="232" alt="스크린샷 2024-01-25 오전 9 25 54" src="https://github.com/WiIIiam278/Velocitab/assets/115847965/e7877ea7-5b58-452d-820f-54c2ef0ec359">

**Comment by waterghost-2046** [comment]
Issue persists

**Comment by alexdev03** [comment]
Open a ticket on discord please

**Comment by xiaozhangup** [comment]
> We believe this is closed by #149 and v1.6.2, if the issue persists please let us know.

version 1.6.2 still have the issue

**Comment by alexdev03** [comment]
> > We believe this is closed by #149 and v1.6.2, if the issue persists please let us know.
> 
> version 1.6.2 still have the issue


Open a ticket on discord please
