### ISSUE TITLE
Error "Failed to dispatch packet (unsupported client or server version)" in proxy logs

### ISSUE THREAD

**Issue by Athar42** [WiIIiam278/Velocitab#140]
Hi,

Recently, I noticed this error message in my Velocity proxy logs : 

> [17:55:56 ERROR] [velocitab]: Failed to dispatch packet (unsupported client or server version)
java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.connection.MinecraftConnection.write(java.lang.Object)'
        at net.william278.velocitab.packet.ScoreboardManager.lambda$dispatchGroupPacket$11(ScoreboardManager.java:267) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at net.william278.velocitab.packet.ScoreboardManager.lambda$dispatchGroupPacket$12(ScoreboardManager.java:259) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.william278.velocitab.packet.ScoreboardManager.dispatchGroupPacket(ScoreboardManager.java:259) ~[?:?]
        at net.william278.velocitab.packet.ScoreboardManager.lambda$updateRole$8(ScoreboardManager.java:169) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
        at net.william278.velocitab.packet.ScoreboardManager.updateRole(ScoreboardManager.java:158) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.lambda$joinPlayer$10(PlayerTabList.java:206) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.lambda$joinPlayer$11(PlayerTabList.java:206) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.lambda$joinPlayer$12(PlayerTabList.java:204) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

- Velocity 3.3.0 - Build 320
- Velocitab 1.5.2
- Client used : Fabric 1.20.4 (tested with my mods enabled, and also with a clean instance, vanilla (no mods at all). Both return that error.

A recent change in Velocity might be the culprit :)

Apart from this error, the plugin seems to work anyways.

**Comment by alexdev03** [comment]
Hi, you can use [this ](https://modrinth.com/plugin/velocitab/version/1.5.2-08501e8) alpha build of velocitab.
