### ISSUE TITLE
 Couldn't pass ProxyInitializeEvent to velocitab

### ISSUE THREAD

**Issue by SkyIce0229** [WiIIiam278/Velocitab#143]
`[00:10:35 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-6d7335b2-b325)...
[00:10:35 INFO]: Loading localizations...
[00:10:35 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[00:10:35 INFO]: Loading plugins...
[00:10:35 INFO]: Loaded plugin minimotd-velocity 2.1.0 by jmp
[00:10:35 INFO]: Loaded plugin papiproxybridge 1.5 by William278
[00:10:35 INFO]: Loaded plugin velocitab 1.6 by William278
[00:10:35 INFO]: Loaded plugin viaversion 4.9.2 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[00:10:35 INFO]: Loaded 4 plugins
[00:10:35 INFO] [papiproxybridge]: PAPIProxyBridge (Velocity) has been enabled!
[00:10:35 ERROR]: Couldn't pass ProxyInitializeEvent to velocitab
net.william278.velocitab.libraries.configlib.ConfigurationException: The configuration file at plugins\velocitab\config.yml does not contain valid YAML.
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:135) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[?:?]
        at net.william278.velocitab.config.ConfigProvider.loadSettings(ConfigProvider.java:63) ~[?:?]
        at net.william278.velocitab.Velocitab.loadConfigs(Velocitab.java:125) ~[?:?]
        at net.william278.velocitab.Velocitab.onProxyInitialization(Velocitab.java:98) ~[?:?]
        at net.william278.velocitab.Lmbda$7.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-325.jar:3.3.0-SNAPSHOT (git-6d7335b2-b325)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-325.jar:3.3.0-SNAPSHOT (git-6d7335b2-b325)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-325.jar:3.3.0-SNAPSHOT (git-6d7335b2-b325)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.snakeyaml.engine.v2.exceptions.YamlEngineException: java.nio.charset.MalformedInputException: Input length = 1
        at org.snakeyaml.engine.v2.scanner.StreamReader.update(StreamReader.java:283) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:239) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:234) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.peek(StreamReader.java:189) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1114) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:292) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:444) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.lambda$produce$1(ParserImpl.java:232) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.produce(ParserImpl.java:232) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.peekEvent(ParserImpl.java:206) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.checkEvent(ParserImpl.java:198) ~[?:?]
        at org.snakeyaml.engine.v2.composer.Composer.getSingleNode(Composer.java:127) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadOne(Load.java:110) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadFromReader(Load.java:134) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:130) ~[?:?]
        ... 12 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
        at java.io.BufferedReader.read1(BufferedReader.java:213) ~[?:?]
        at java.io.BufferedReader.read(BufferedReader.java:287) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.update(StreamReader.java:246) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:239) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:234) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.StreamReader.peek(StreamReader.java:189) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1114) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:292) ~[?:?]
        at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:444) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.lambda$produce$1(ParserImpl.java:232) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.produce(ParserImpl.java:232) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.peekEvent(ParserImpl.java:206) ~[?:?]
        at org.snakeyaml.engine.v2.parser.ParserImpl.checkEvent(ParserImpl.java:198) ~[?:?]
        at org.snakeyaml.engine.v2.composer.Composer.getSingleNode(Composer.java:127) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadOne(Load.java:110) ~[?:?]
        at org.snakeyaml.engine.v2.api.Load.loadFromReader(Load.java:134) ~[?:?]
        at net.william278.velocitab.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:130) ~[?:?]
        ... 12 more`

**Comment by WiIIiam278** [comment]
Read the upgrade instructions; You must regenerate your server config.yml files.
