### ISSUE TITLE
Bedrock and java crossplay doesn't work with this plugin Idk why

### ISSUE THREAD

**Issue by Justkonijn** [WiIIiam278/Velocitab#151]

**Comment by alexdev03** [comment]
What do you mean it doesn't work? Send a screenshot on both platforms. Are you using the latest version of velocitab and velocity?

**Comment by Justkonijn** [comment]
And multi verion my servers run on 1.20.1 and i cant join lower or higher with viaversion all versions

**Comment by Justkonijn** [comment]
![Screenshot 2024-01-31 084023](https://github.com/WiIIiam278/Velocitab/assets/99992901/6ad3d80f-bff1-4cfb-ad51-8878c4d79e2f)
![image](https://github.com/WiIIiam278/Velocitab/assets/99992901/c4c2aedc-7a34-4cd5-8da0-17573fed9f6b)
![image](https://github.com/WiIIiam278/Velocitab/assets/99992901/177d40cf-9931-4632-8296-7be8f858f94e)

**Comment by Justkonijn** [comment]
And i run 1.4.1 velocitab and 3.0.0 snapshot velocity

**Comment by alexdev03** [comment]
You are running an outdated version of velocitab(released 7 months ago lol) and an outdated velocity version. Please update both.

> And i run 1.4.1 velocitab and 3.0.0 snapshot velocity

**Comment by Justkonijn** [comment]
Okay and i mean velocity 3.3.0

**Comment by Justkonijn** [comment]
Whatt..... what's it now

![image](https://github.com/WiIIiam278/Velocitab/assets/99992901/65853cc6-e215-42bd-b294-4a7226c1828b)

**Comment by alexdev03** [comment]
Probably you are using minimessage codes without using minimessage as formatter, check config.

**Comment by Justkonijn** [comment]
Oo okay thx everything is working now!!!

**Comment by Justkonijn** [comment]
Exept for 1 thing 

[08:04:21 ERROR]: Exception in task net.william278.velocitab.tab.PlayerTabList$$Lambda$1467/0x00007f6a488befc0@418dc2fe by plugin Velocitab
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "format" is null
        at net.william278.velocitab.config.Placeholder.replace(Placeholder.java:97) ~[?:?]
        at net.william278.velocitab.player.TabPlayer.getDisplayName(TabPlayer.java:108) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.updatePlayerDisplayName(PlayerTabList.java:310) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.updateDisplayNames(PlayerTabList.java:331) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.updateGroupPlayers(PlayerTabList.java:397) ~[?:?]
        at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$36(PlayerTabList.java:365) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-345.jar:3.3.0-SNAPSHOT (git-38558783-b345)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
        

[08:05:39 ERROR]: Exception in task net.william278.velocitab.tab.PlayerTabList$$Lambda$1467/0x00007f6a488befc0@418dc2fe by plugin Velocitab
java.lang.NullPointerException: null


        ^^^^^^^
is in the velocity logs

**Comment by alexdev03** [comment]
Open a ticket on discord

**Comment by Justkonijn** [comment]
Done i am on a alt BTW Discord name > Nood/danger

its just a alt that can leave emargences from my staff team
