### ISSUE TITLE
Issue with Viaversion 5.1.0 (but random ?)

### ISSUE THREAD

**Issue by Athar42** [WiIIiam278/Velocitab#227]
Hi there,

Just want to report a potential "bug".

I did update ViaVersion/Backward on all my servers, behind a Velocity Proxy (3.4.0, latest build 445) and, only on one specific server, the transfert fail.

On two servers, it work, on 4 others it fail.

I did tried without any plugin on the backend servers (except for Via) and... not working same issue.

From Velocity :
```
exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@75b73e50
io.netty.handler.codec.CorruptedFrameException: Error decoding class net.william278.velocitab.packet.UpdateTeamsPacket Direction CLIENTBOUND Protocol 1.21.2 State PLAY ID 60
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: No adapter found for protocol version 1.21.2
        at net.william278.velocitab.packet.ScoreboardManager.lambda$getPacketAdapter$1(ScoreboardManager.java:87) ~[?:?]
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.william278.velocitab.packet.ScoreboardManager.getPacketAdapter(ScoreboardManager.java:87) ~[?:?]
        at net.william278.velocitab.packet.UpdateTeamsPacket.decode(UpdateTeamsPacket.java:216) ~[?:?]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity.jar:3.4.0-SNAPSHOT (git-69ee655d-b445)]
        ... 30 more
```

What I did not understand is, why it work on some servers and not with other (same Paper build, 1.21.1-128, and mostly, same addons and datapacks if any (some failed didn't have any specific plugins and/or datapacks).

From the error, that's quite normal as the new minecraft version isn't supported yet by this plugin I guess, so just to point out this issue :) (also : When someone did connect, the client running 1.21.3 get disconnected too, probably the same issue)

**Comment by WiIIiam278** [comment]
Hey there -- answer is simple; 1.21.2/3 is not supported yet. Please check in for updates soon.

That's all~!
