### ISSUE TITLE
Protocolize packet seemingly failed to decode

### ISSUE THREAD

**Issue by Emibergo02** [WiIIiam278/Velocitab#3]
Encountered this error:
```
[23:04:30 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[23:04:30 ERROR] [Protocolize]: Protocolize 2.2.5:598
[23:04:30 ERROR] [Protocolize]: Stream Direction: UPSTREAM
[23:04:30 ERROR] [Protocolize]: InboundConnection: [connected player] Unnm3d (/31.156.170.216:60227), ServerConnection: null
[23:04:30 ERROR] [Protocolize]: Protocol version: 1.19.3
[23:04:30 ERROR]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.entities" is null
netty errors blah blah blah
[23:04:30 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.entities" is null
[23:04:30 ERROR]:       at net.william278.velocitab.packet.UpdateTeamsPacket.write(UpdateTeamsPacket.java:117)
[23:04:30 ERROR]:       at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.encode(VelocityProtocolizePacket.java:66)
[23:04:30 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:54)
[23:04:30 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32)
[23:04:30 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[23:04:30 ERROR]:       ... 60 more
[23:04:30 ERROR]: [server connection] Unnm3d -> survival-spawn: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@7c8fbec5
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
```
tomorrow i'll try to find the cause. if you want a tester here am i

**Comment by WiIIiam278** [comment]
@Emibergo02 Did you test this on the latest commit? Further, were you playing on a 1.19.3 client? What velocity version were you running?
Duly note Protocolize 2.2.5 is required (you must build Protocolize@master at the moment).

**Comment by Emibergo02** [comment]
yep. tested latest commit now. 1.19.3 client. latest protocolize 2.2.5. running Velocity-NoChatSigning latest commit

**Comment by Emibergo02** [comment]
```
[12:22:07 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[12:22:07 ERROR] [Protocolize]: Protocolize 2.2.5:599
[12:22:07 ERROR] [Protocolize]: Stream Direction: DOWNSTREAM
[12:22:07 ERROR] [Protocolize]: InboundConnection: null, ServerConnection: [server connection] Unnm3d -> survival-spawn
[12:22:07 ERROR] [Protocolize]: Protocol version: 1.19.3
[12:22:07 ERROR]: io.netty.handler.codec.CorruptedFrameException: Error decoding class dev.simplix.protocolize.velocity.packets.GeneratedUpdateTeamsPacketWrapper Direction CLIENTBOUND Protocol 1.19.3 State PLAY ID 56
[12:22:07 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131)
[12:22:07 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86)
[12:22:07 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:22:07 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:22:07 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:22:07 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:22:07 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[12:22:07 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[12:22:07 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[12:22:07 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:22:07 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[12:22:07 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:22:07 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[12:22:07 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[12:22:07 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[12:22:07 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[12:22:07 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[12:22:07 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:22:07 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[12:22:07 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[12:22:07 ERROR]: Caused by: io.netty.handler.codec.CorruptedFrameException: Protocolize is unable to read packet net.william278.velocitab.packet.UpdateTeamsPacket at protocol version 1.19.3 in direction CLIENTBOUND
[12:22:07 ERROR]:       at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.decode(VelocityProtocolizePacket.java:58)
[12:22:07 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84)
[12:22:07 ERROR]:       ... 34 more
[12:22:07 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.entities" is null
[12:22:07 ERROR]:       at net.william278.velocitab.packet.UpdateTeamsPacket.read(UpdateTeamsPacket.java:95)
[12:22:07 ERROR]:       at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.decode(VelocityProtocolizePacket.java:49)
[12:22:07 ERROR]:       ... 35 more
```
This is with `-Dvelocity.packet-decode-logging=true` flag on Velocity

**Comment by WiIIiam278** [comment]
@Emibergo02 Can you try again with the latest commit?

**Comment by Emibergo02** [comment]
Of course. All working as expected. I'm closing this issue
